# need 4 gpus

project: coconut
save_path: output_dir
name: prompt-classifier-coconut

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 3
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: /root/.cache/kagglehub/models/qwen-lm/qwen2.5/transformers/0.5b/1
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: /root/competition/coconut/data/train.json
val_path: /root/competition/coconut/data/train.json
reset_optimizer: True
batch_size_training: 1
debug: False
gradient_accumulation_steps: 1
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01